### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by ConnorSiXiong** [TanyaChutani/SSD-Tensorflow#2]
Hi Tanya,

in the first three boxes, the data is not allowed to download,

it says 'Maybe you need to change permission over 'Anyone with the link'?'

can you help?

Thank you

**Comment by TanyaChutani** [comment]
Hey Alex, 

I am not owner of this dataset. I have used dataset from here [](https://github.com/eg4000/SKU110K_CVPR19).

**Comment by TanyaChutani** [comment]
Hey Alex,

I am not owner of this dataset. I have used dataset from here [](https://github.com/eg4000/SKU110K_CVPR19)

**Comment by TanyaChutani** [comment]
Hey Alex,

I am not owner of this dataset. I have used dataset from here https://github.com/eg4000/SKU110K_CVPR19.
